config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    collection do
      get 'complete'
      get 'slack'
    end
  end

  root to: 'tasks#index'

  get 'reminds/new', to: 'reminds#new'
  get '/reminds/slack', to: 'reminds#slack'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slack.rb
class Slack
  def self.send_message(text)
    uri = Addressable::URI.parse(Settings.slack.test)
    rqs = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json', )
    rqs.body = "{'text': '#{text}'}"
    Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') { |http|
      res = http.request(rqs)
    }
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :date, presence: true
  validates :plan_time, numericality: { only_integer: true }, allow_blank: true
  validates :actual_time, numericality: { only_integer: true }, allow_blank: true
  validates :memo, length: { maximum: 200 }, allow_blank: true
  validates :importance, numericality: { less_than_or_equal_to: 100 }
  validates :urgency, numericality: { less_than_or_equal_to: 100 }

  enum progress: [:planed, :doing, :done, :sent]
  enum frequency: [:today, :every_week, :every_day]
  enum purpose: [:work, :challenge, :study]

  scope :today, -> { where(date: Date.current).order(urgency: :desc) }
  scope :not_today, -> { where.not(date: Date.current).order(:date) }
  scope :high_priority, -> { where("urgency > 50") }
  scope :row_priority, -> { where("urgency <= 50") }
  scope :planed, -> { where(progress: :planed) }
  scope :doing, -> { where(progress: :doing) }
  scope :done, -> { where(progress: :done) }
  scope :sent, -> { where(progress: :sent) }
  scope :not_finished, -> { planed.or(doing) }
  scope :finished, -> { done.or(sent)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reminds_controller.rb
class RemindsController < ApplicationController
  def new
  end

  def slack
    uri = Settings.slack.test
    types = ["m", "n", "c", "l"]
    text = ""
    types.each do |type|
      case type
      when "m"
        text << "【依頼】\n"
      when "n"
        text << "【通常issuePJ】\n"
      when "c"
        text << "【チャレンジPJ】\n"
      when "l"
        text << "【学習PJ】\n"
      end
      i = 1
      params[type].to_i.times do
        n = i.to_s
        title, progress, day = "#{type + n}_title", "#{type + n}_progress", "#{type + n}_day"
        text << "#{params[title]}  #{params[progress]}  #{params[day]} \n"
        i += 1
      end
    end

    uri = Addressable::URI.parse(uri)
    rqs = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json', )
    rqs.body = "{'text': '#{text}'}"
    Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') { |http|
      res = http.request(rqs)
    }

    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @today_tasks = Task.today.not_finished
    @not_today_tasks = Task.not_today.not_finished
  end

  def complete
    @finished_today_tasks = Task.today.finished
    @finished_not_today_tasks = Task.not_today.finished
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  def slack
    not_sent_today_tasks = Task.done
    return redirect_to complete_tasks_path, notice: "all tasks were sent" if not_sent_today_tasks.blank?
    grouped_tasks = not_sent_today_tasks.group_by{ |task| task.purpose }
    text = ""
    if grouped_tasks["work"].present?
      text << "【業務】 \n"
      grouped_tasks["work"].each do |work_task|
        text <<
        "#{work_task.title}  #{work_task.date} \n"
      end
    end
    if grouped_tasks["challenge"].present?
      text << "【チャレンジ】 \n"
      grouped_tasks["challenge"].each do |challenge_task|
        text <<
        "#{challenge_task.title}  #{challenge_task.date} \n"
      end
    end
    if grouped_tasks["study"].present?
      text << "【学習】 \n"
      grouped_tasks["study"].each do |study_task|
        text <<
        "#{study_task.title}  #{study_task.date} \n"
      end
    end

    Slack.send_message(text)

    not_sent_today_tasks.update_all(progress: :sent)

    redirect_to complete_tasks_path
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(
        :title, :date, :plan_time, :actual_time, :importance,
        :urgency, :progress, :frequency, :memo, :purpose
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminds_helper.rb
module RemindsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "tasks", tasks_path %></li>
        <li><%= link_to "complete", complete_tasks_path %></li>
        <li><%= link_to "report", "#" %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div class="col s12">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/reminds/new.html.erb
<div class="container">
  <h1>報告</h1>


  <%= form_tag "/reminds/slack", method: :get do %>
    <h2>依頼</h2>
    <%= react_component("Form", {prefix: "m"}) %>

    <h2>通常</h2>
    <%= react_component("Form", {prefix: "n"}) %>

    <h2>チャレンジ</h2>
    <%= react_component("Form", {prefix: "c"}) %>

    <h2>学習</h2>
    <%= react_component("Form", {prefix: "l"}) %>

    <%= submit_tag "slackで送る", class: "btn btn-default" %>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tbody>
      <tr>
        <td class="input-field col s4">
          <%= f.text_field :title %>
          <%= f.label :title %>
        </td>
        <td class="input-field col s4">
          <%= f.date_field :date, class: "datepicker" %>
          <%= f.label :date %>
        </td>
      </tr>
      <tr>
        <td class="input-field col s4">
          <%= f.select :plan_time, [
            ["1Man-Hr", 1], ["2Man-Hr", 2], ["3Man-Hr", 3]
          ] %>
          <%= f.label :plan_time %>
        </td>
        <td class="input-field col s4">
          <%= f.radio_button :frequency, :today %>
          <%= f.label :frequency_today, "today only" %>
          <%= f.radio_button :frequency, :every_week %>
          <%= f.label :frequency_every_week, "every week" %>
          <%= f.radio_button :frequency, :every_day %>
          <%= f.label :frequency_every_day, "every day" %>
        </td>
        <td class="input-field col s4">
          <%= f.radio_button :purpose, :work %>
          <%= f.label :purpose_work, "work" %>
          <%= f.radio_button :purpose, :challenge %>
          <%= f.label :purpose_challenge, "challenge" %>
          <%= f.radio_button :purpose, :study %>
          <%= f.label :purpose_study, "study" %>
        </td>
      </tr>
      <tr>
        <td class="input-field col s4">
          <%= f.range_field :importance, in: 0..100 %>
          <%= f.label :importance %>
        </td>
        <td class="input-field col s4">
          <%= f.range_field :urgency, in: 0..100 %>
          <%= f.label :urgency %>
        </td>
      </tr>
      <tr>
        <td class="input-field col s12">
          <%= f.text_area :memo, class: "materialize-textarea" %>
          <%= f.label :memo %>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_tasks.html.erb
<ul class="collection">
  <li class="collection-item avatar row task-collection-item">
    <div class="first-content col s12">
      <div class="col s1 task-icon-wrapper">
        <% if task.purpose == "work" %>
          <i class="material-icons task-icon">work</i>
        <% elsif task.purpose == "challenge" %>
          <i class="material-icons task-icon">trending_up</i>
        <% elsif task.purpose == "study" %>
          <i class="material-icons task-icon">border_color</i>
        <% end %>
      </div>
      <div class="task-summary col s6">
        <p class="title">
          <%= task.title %>
          <% if task.urgency > 50 %>
            <span class="new badge red" data-badge-caption="">urgency</span>
          <% end %>
          <span class="secondary-badge new badge blue" data-badge-caption=""><%= task.progress %></span>
        </p>
        <p><%= task.plan_time %></p>
        <p class="trancate"><%= task.memo %></p>
      </div>
      <div class="input-field collection-item-done col s3">
        <%= form_for task, class: "row col s12" do |f| %>
          <div class="input-field col s10 task-input-field">
            <%= f.select :actual_time, [
              ["doing", nil], ["1Man-Hr", 1], ["2Man-Hr", 2], ["3Man-Hr", 3]
            ] %>
            <%= f.label :actual_time%>
            <%= f.hidden_field(:progress, value: :done) %>
          </div>
          <div class="input-field col s2 task-input-field">
            <%= button_tag type: :submit, class: "btn waves-effect" do %>
              <i class="small material-icons">done</i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="secondary-content bottom-icon">
      <%= link_to task do %>
        <i class="small material-icons">visibility</i>
      <% end %>
      <%= link_to edit_task_path(task) do %>
        <i class="small material-icons">mode_edit</i>
      <% end %>
      <%= link_to task, method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="small material-icons">delete</i>
      <% end %>
    </div>
  </li>
</ul>

app/views/tasks/complete.html.erb
<div class="tasks-complete">
  <p id="notice"><%= notice %></p>

  <h1>Complate Tasks</h1>

  <%= link_to slack_tasks_path, disabled: false, disable_with: "Please wait...", class: "btn waves-effect" do %>
    <i class="small material-icons">send</i>
  <% end %>

  <h2>Today's Tasks</h2>
  <%= render partial: "tasks", collection: @finished_today_tasks, as: :task %>


  <h2>All Tasks</h2>
  <%= render partial: "tasks", collection: @finished_not_today_tasks, as: :task %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to edit_task_path(@task) do %>
  <i class="small material-icons">visibility</i>
<% end %>
<%= link_to tasks_path do %>
  <i class="small material-icons">list</i>
<% end %>

app/views/tasks/index.html.erb
<div class="tasks">
  <p id="notice"><%= notice %></p>

  <h1>Tasks</h1>

  <%= link_to new_task_path do %>
    <i class="small material-icons">playlist_add</i>
  <% end %>

  <h2>Today's Tasks</h2>
  <%= render partial: "tasks", collection: @today_tasks, as: :task %>

  <h2>All Tasks</h2>
  <%= render partial: "tasks", collection: @not_today_tasks, as: :task %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to tasks_path do %>
  <i class="small material-icons">list</i>
<% end %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card blue-grey darken-1">
  <div class="card-content white-text">
    <span class="card-title"><%= @task.title %></span>
    <p><%= @task.memo %></p>
  </div>
  <div class="card-action">
    <a href="#">This is a link</a>
    <a href="#">This is a link</a>
    <i class="material-icons right activator">more_vert</i>
  </div>
  <div class="card-reveal">
    <span class="card-title grey-text text-darken-4"><%= @task.title %><i class="material-icons right">close</i></span>
    <p><%= @task.memo %></p>
  </div>
</div>

<%= link_to edit_task_path(@task) do %>
  <i class="small material-icons">mode_edit</i>
<% end %>
<%= link_to tasks_path do %>
  <i class="small material-icons">list</i>
<% end %>